### ISSUE TITLE
Google Chromium

### ISSUE THREAD

**Issue by noahbuscher** [burocratik/outdated-browser#11]
It says my Google Chromium browser was outdated, though I just updated it to the latest version. I generally I use this over Google Chrome. Why? I don't know.

Would it be possible to add this to the list of browsers you accept as "newer"?

**Comment by freechelmi** [comment]
Please Reopen.

tested Chromium 70 on https://www.free.fr/freebox/ , says outdated

Tested Your local demos  : all OK except for NOAjax .

So that's a false positive

**Comment by sctfic** [comment]
+1
