### ISSUE TITLE
Missing content after resizing Google Chrome Browser.

### ISSUE THREAD

**Issue by nahody** [burocratik/outdated-browser#137]
After resizing the width and height of my Google Chrome Browser Version 39.0.2171.95 (64-bit) on OS X 10.10 the content is missing!
Only the menu Icon is visible. After reload it work till next resizing.

**Comment by alexprg** [comment]
Hi there,
I have the same configuration as you (OS and Chrome) and I can't replicate that. All shows up if I resize. We will try to replicate that in other machines.
Thanks 
Cheers
