### ISSUE TITLE
Targeting IE version < 11

### ISSUE THREAD

**Issue by turboteddy** [burocratik/outdated-browser#143]
If I understand the README.md using ´borderImage´ would target any IE version below 11. However, even when IE 11 is used, the warning is displayed. Is it me who misunderstands the semantics of the README.md ("Lower Than"), or is this a bug?

Keep up the good work!

**Comment by alexprg** [comment]
Hi,
Thank you for the :+1:  regarding this project.
You understood everything perfectly: with 'borderImage' , we shouldn't have the warning on IE11. 
In the tests we did it works fine, just double jeck again and is ok: http://buro.pt/ZEXn
Can you send us a link of your project for us to check?
Cheers

**Comment by turboteddy** [comment]
Thanks for the quick reply, @alexprg ! Sorry, but the code isn't staged yet, so not available online.
I guess I'll have to debug a bit more. Will let you know if I find anything of interest.

**Comment by alexprg** [comment]
Welcome :+1: 
In your our demo files with didn't use that meta and it works fine. Keep us posted please ;)
Thank you man
