### ISSUE TITLE
npm (requirejs and browserify support)

### ISSUE THREAD

**Issue by Grafikart** [burocratik/outdated-browser#144]
Hi,

Before coding anything I would like to know if you are interested by adding browserify and requirejs support for outdated-browser it would allow people to use a simple 

    require('outdatedbrowser'); 

If you find this feature interesting could you tell me what task do you use to minify the script ?

**Comment by alexprg** [comment]
Hi @Grafikart 
That would be great.
Being a simple script we use CodeKit to create minify files.
Cheers

**Comment by mikemaccana** [comment]
Hi @Grafikart and @alexprg 

I have a forked version of updated-browser project on npm (with some significant chanegs and feature enahancements). See https://www.npmjs.com/package/outdated-browser-rework

**Comment by Grafikart** [comment]
@mikemaccana Nice. 

I guess we can close this PR so :(

**Comment by alexprg** [comment]
@mikemaccana 
Thanks man I will check that asap ;)

**Comment by mnquintana** [comment]
Any chance of this happening in the official repo? It'd be super useful to be able to `require` this like a standard Node module.

**Comment by alexprg** [comment]
@mnquintana hopefully soon we will, but with some differences in the approach.
Cheers
