### ISSUE TITLE
Understanding the JS styling

### ISSUE THREAD

**Issue by mikemaccana** [burocratik/outdated-browser#147]
Hi I'm working on a modified version of updated browser to support mobile, and add an explicit browser version matrix. I can understand the `onmouseover` and `onmouseout` styles - apparently IE6 does not support :hover. 

But I'm having trouble explaining why the other JS-based styling exists  `buttonUpdate.style.color = textColor;` etc - why isn't the CSS enough? 

Could you explain? Thanks!

**Comment by mikemaccana** [comment]
Actually it seems IE6 understands `:hover` on anchors, and since the button is an `a` element :hover would do it. The plot thickens!

**Comment by alexprg** [comment]
The idea is that you choose the colors without having to edit the css file.
cheers
