### ISSUE TITLE
Add OS detection (Code included!)

### ISSUE THREAD

**Issue by StephenBrown2** [burocratik/outdated-browser#153]
I realize this has been somewhat discussed before in #30 and #32, and I really wish I could simply post a pull request RE: #108, but here is a small snippet of code for detecting the Desktop OS/Platform that the browser is running. I've tested this with my own code and by pulling down the source of outdatedbrowser.com, and it works well to prune irrelevant Browsers (Namely Safari and IE) when on an incompatible OS (Tested on Linux and Mac, specifically). Please feel free to implement on outdatedbrowser.com.

Note: If you would prefer to use jQuery for the array searching, you could replace the 'contains' function with $.inArray() like such:

    - if (!contains(os, arroslist)) {
    + if ($.inArray(os, arroslist) != -1) {

---

    // Assume the superior OS (for cross-platform default selection)
    var os = 'linux';
    if (navigator.appVersion.indexOf("Win") != -1) os = "windows";
    if (navigator.appVersion.indexOf("Mac") != -1) os = "mac";
    if (navigator.appVersion.indexOf("X11") != -1) os = "linux";
    if (navigator.appVersion.indexOf("Linux") != -1) os = "linux";

    function contains(obj, a) {
        var i = a.length;
        while (i--) {
            if (a[i] === obj) {
                return true;
            }
        }
        return false;
    }

    var browsers = document.getElementsByClassName('browser');
    var arroslist = [];
    var oslist = [];
    var i = browsers.length;
    while (i--) {
        oslist = browsers[i].getElementsByTagName('li');
        arroslist.length = 0;
        for (var j = 0; j < oslist.length; j++) {
            arroslist.push(oslist[j].className);
        }
        if (!contains(os, arroslist)) {
            browsers[i].parentNode.removeChild(browsers[i]);
        }
    }

**Comment by alexprg** [comment]
@StephenBrown2 thanks for the code :+1: 
What we have found is more options/exceptions we try to implement it becomes harder to maintain and test the site. If we were targeting modern OS/Browsers all would be easy, mas testing in old OS / Browsers it becomes overwhelming. 
Maybe in the future we will implement that feature. 
Thank you for the input :)
Cheers
