### ISSUE TITLE
Add 'outdated' div in JavaScript rather than into HTML

### ISSUE THREAD

**Issue by joshfarrant** [burocratik/outdated-browser#155]
It would be useful if the '#outdated' div was added by the outdatedbrowser.js file, rather than having to add it manually into the HTML.

It's a simple change and I can't see any immediate issues with it. It just takes 3 new lines at the top of the file.

```
var outdatedBrowser = function(options) {

    var div = document.createElement("div");
    div.id = "outdated";
    document.body.appendChild(div);

    var outdated = document.getElementById("outdated");

    [...]
```

This would be quite useful when using the package with Ember and QUnit where, in it's current state, it causes tests to fail due to the way documents are loaded.

Let me know your thoughts - I'd be happy to submit a pull request too.

**Comment by alexprg** [comment]
Hi there,
Thanks for the contribution :+1: 
Did you test in older browsers? IE6, etc?
Doing that way we would have that div just after the body tag, and for something not important for SEO I would rather have as we have. I personally use the plugin with that div and it's content in the html = less js = less probability for errors in older browsers = faster to load the plugin if the connection is not very good. But that's me ;) 
Maybe we could do a release for Ember and QUnit? But we have to test in very old browsers first :S

**Comment by joshfarrant** [comment]
Not had chance to try it in IE6, but I agree it would need testing first. I can't see any obvious compatibility issues, as both .createElement() and .appendChild() are supported in old browsers according to W3Schools:

http://www.w3schools.com/jsref/met_node_appendchild.asp
http://www.w3schools.com/jsref/met_document_createelement.asp

Appreciate your point about SEO too. For web apps this is less of an issue, so maybe a separate release would be worth considering after testing in older browsers?

**Comment by alexprg** [comment]
If I had to list here all the things that are online saying:  "works on IE6" and it fails badly ehehehe would be a long list!!! :D .The reason the js of this plugin is not fully optimized, and with the latest js specs, is that the main purpose of this plugin is to work on old browsers! The newest browsers don't need this. So we have to test everything and make lots of concessions. In resume: I think that will be no problem, but it has to be tested (IE6 to IE11) and tested.

I really appreciate your help, and would be cool to make a release with this feature. I would appreciate if you could test it on Ember and QUnit. Then we could make a link like we did for plugins like Wordpress, Ruby, etc. What do you think?
Thank you for the help ;)

**Comment by alexprg** [comment]
Tested in IE6 and in real projects with more js dependencies and I got some performance problems + not working properly for IE6.
Although this is a good approach we have to keep in mind that this is for old browsers, the simpler we keep less probability of having problems.
Thanks :+1:
