### ISSUE TITLE
Poposal

### ISSUE THREAD

**Issue by ondoheer** [burocratik/outdated-browser#156]
Spanish is spoken among so many different countries with so many different slangs that we tend to use different ways to refer to the same. 

When I donwloaded the latest version of outdatedbrowser I was surprised to see the text displaying as something that must have come out of an automatic translator, then I realized that was the way to express "outdated" in other Latin countries.

Would it be posible to add specific per country Spanish variations?
I mean, It's just adding the right UTF to the end of each language file, I didin't want to write a es_PE.html file and send a pull request without asking first.

**Comment by luisalima** [comment]
@ondoheer , it might be worth it to take a look at and think a bit about the standard locale codes... which I'm not sure which ones should be picked:

http://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes

See also 

https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale

I'm using the rails standard in the rails ruby gem, which I just updated today; this decision will affect the gem so it would be great if you guys could ping me with the standard you pick.

**Comment by alexprg** [comment]
Hi there, 
Thanks for the feedback.
1 - for the lang atribute we use: 
http://rusticode.com/2013/04/11/html5-iso-language-code-table-language-culture-names/

2- for the language URL we use the country code top-level domain (easy for people guess then lang codes)

**Comment by ondoheer** [comment]
ok, i will write the *pe* template then and make a pull request.

**Comment by alexprg** [comment]
@ondoheer 
Gracias :+1:
