### ISSUE TITLE
"Out of date" should not be hyphenated in English

### ISSUE THREAD

**Issue by jaydee18** [burocratik/outdated-browser#164]
The primary message displays as "YOUR BROWSER IS OUT-OF-DATE!"
The term "out of date" contains incorrect hyphenation and is technically not grammatical. It should simply be output as "YOUR BROWSER IS OUT OF DATE!"

**Comment by alexprg** [comment]
hi @jaydee18 
Thank you for the feedback. 
So "your browser is out of date" but "you have a out-of-date browser" ? Is this right? Not easy to understand this! :/ 

http://www.oxforddictionaries.com/definition/english/out-of-date
http://www.merriam-webster.com/dictionary/out-of-date

**Comment by jaydee18** [comment]
Yes, that's correct.

"YOUR BROWSER IS OUT OF DATE!"

or

"YOU HAVE AN OUT-OF-DATE BROWSER!"

The first option is better though. The second one sounds a bit strange.
