### ISSUE TITLE
Don't offer Safari to Windows users

### ISSUE THREAD

**Issue by jaydee18** [burocratik/outdated-browser#166]
Is it not possible to be smarter about how this is displayed? Perhaps preventing a click or a message that says "Safari is not available to Windows users".

At the moment, if you click on the Safari link, you are taken to an Apple downloads page where there is no mention of Safari. This will confuse some users.

**Comment by brunoamorim** [comment]
Hi @jaydee18, i understand your point but if you take the Safari bar, you have to take the Internet Explorer too for Mac users and the design would become unbalanced.

Thanks for your input.
B.

**Comment by jaydee18** [comment]
Unbalanced? It's not good practice to put visual design ahead of usability. You shouldn't be offering Safari to Windows users nor IE to Mac users.

**Comment by alexandre-works** [comment]
@jaydee18 I understand your point of view, but you also must know how unreliable is to do any kind of OS/Browser detection - Specially  for older browsers (mind that the main purpose of this site is for older browsers, ie6, 7, 8, etc)!
It seams that users are more cleaver then sometimes we think. In our analytics we do not see any significant number Mac users clicking on IE or WIN users clicking in Safari (people stick with the browser that they already have).  
Anyway thank you so much for your input :+1: 
Cheers

**Comment by jaydee18** [comment]
Yep sure, that maybe well and true, but there’s nothing stopping you from putting a small disclaimer on each browser pane that reads something like “Available only to Windows users” for IE and “Available only to MAC users” for Safari.

**Comment by jaydee18** [comment]
Actually, I just noticed you do have something like that with the icons at the bottom of each pane. I think that’s good but it’s not really noticeable unless you’re looking hard for it. Perhaps it needs to be more prominent - like just under the “Download” link.
