### ISSUE TITLE
Using out of date logo of Safari.

### ISSUE THREAD

**Issue by Haroenv** [burocratik/outdated-browser#168]
I extracted the current one from my install

https://www.dropbox.com/s/uk1cxpx5mjg4yov/compass.icns?dl=0

**Comment by brunoamorim** [comment]
Hi @Haroenv, thanks for this. We'll update the logo as soons as possible!

Regards,
B.

**Comment by brunoamorim** [comment]
@Haroenv we already updated the Safari logo. Thanks for your collaboration! 

Kind regards,
B.

**Comment by Haroenv** [comment]
great :)

**Comment by Haroenv** [comment]
No problem, it wasn’t much work, but I couldn’t find where in the source you used the images

Haroen
