### ISSUE TITLE
New to github but want to contribute with translations

### ISSUE THREAD

**Issue by keremdemirer** [burocratik/outdated-browser#170]
Hi,

I'd like to contribute to Turkish translations for plugin and website. I already completed, can you please guide me to push codes?

Best,
Kerem

**Comment by alexprg** [comment]
Hi there,
Thank you for the help.
For the plugin: https://github.com/burocratik/outdated-browser/tree/feature/languages, just fork and add the new language
For the site: https://github.com/burocratik/outdated-browser/tree/feature/languages-website , for and add language.
If you having problems you can always write the translation here and I will add the files ;)
Cheers
Alex

**Comment by keremdemirer** [comment]
Hi Alex,

I just commit these. I could not test properly because php is not installed on my machine. Hope everything is OK.

plugin: 
https://github.com/keremdemirer/outdated-browser/commit/8d386b5ec7e4663fa3740189378c2a8f515149f0

website:
https://github.com/keremdemirer/outdated-browser/commit/278fc312f98810fa023f00d37d73c1f112e748ca

Cheers,
Kerem

**Comment by alexprg** [comment]
@keremdemirer 
Thank you so much, will do asap.
