### ISSUE TITLE
Feature Detection is only working for Internet Explorer (what about other browsers?)

### ISSUE THREAD

**Issue by pligor** [burocratik/outdated-browser#174]
I tried testing your plugin by getting the out-of-the-box demo folder and embedding it in my own server and here is the link: http://george.pligor.com/outdated_browser_test/demo/  
(this link might have been removed the time you are reading this post)

The test was with a very old firefox, version 15 (note that currently firefox is version 38).
No panel is triggered (ajax or no ajax) and here is what you can see:
![outdated browser - mozilla firefox_2015-06-02-00 33 51](https://cloud.githubusercontent.com/assets/1448173/7923916/b1d0d17a-08bf-11e5-8143-d034af2923f9.png)

Also you can verify yourself that one of my own websites like pligor.com (and I am sure many others like google maps) is seriously malfunctioning under such an old browser like firefox v15. Here is a screenshot of how http://pligor.com looks like and of course nothing is triggered either.
![pligoropoulos - mozilla firefox_2015-06-02-00 32 20](https://cloud.githubusercontent.com/assets/1448173/7923948/0f33a9aa-08c0-11e5-8712-d36a19b0ae1c.png)

I could say that feature detection worked correctly for Internet Explorer but still this is not enough to ensure maximum user experience.

#### Suggestion

After my own investigation I read some things that Modernizr is being used for feature detection. Would a marriage between your plugin and modernizr make sense?

#### My own temporary and non-recommended solution
Finally I ended up using the non-recommended solution of checking for browser version instead of feature detection and the corresponding javascript is shared below:
```
/**
 * Created by pligor on 6/1/15.
 */

function MyOutdatedBrowser() {
    //TODO create a public api to have these set from the cloud rather than having them hardcoded in typescript
    var browsers = {
        GoogleChrome: {
            name: "chrome",
            version: 43
        },
        MozillaFirefox: {
            name: "firefox",
            version: 38
        },
        InternetExplorer: {
            name: "msie",
            version: 11
        },
        AppleSafari: {
            name: "safari",
            version: 8
        },
        Opera: {
            name: "opera",
            version: 29
        }
    }

    function getBrowserKeys() {
        return Object.getOwnPropertyNames(browsers)
    }

    function isBrowserOutdated(curBrowser) {
        var curBrowserName = curBrowser.name.toLowerCase()

        var keys = getBrowserKeys()

        for(var i=0; i< keys.length ; i++) {
            var browser = browsers[keys[i]]

            if(curBrowserName === browser.name) {
                return curBrowser.version < browser.version;
            } else {
                //continue
            }
        }

        return true;  //browser is found and version is equal or great than ours
    }

    /**
     * http://stackoverflow.com/a/16938481/720484
     * @returns {any}
     */
    function get_browser_info() {
        var ua = navigator.userAgent, tem, M = ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i) || [];
        if (/trident/i.test(M[1])) {
            tem = /\brv[ :]+(\d+)/g.exec(ua) || [];
            return {name: 'IE ', version: (tem[1] || '')};
        }
        if (M[1] === 'Chrome') {
            tem = ua.match(/\bOPR\/(\d+)/)
            if (tem != null) {
                return {name: 'Opera', version: tem[1]};
            }
        }
        M = M[2] ? [M[1], M[2]] : [navigator.appName, navigator.appVersion, '-?'];
        if ((tem = ua.match(/version\/(\d+)/i)) != null) {
            M.splice(1, 1, tem[1]);
        }
        return {
            name: M[0],
            version: M[1]
        };
    }

    function addLoadEvent(func) {
        var oldonload = window.onload;
        if (typeof window.onload != 'function') {
            window.onload = func;
        } else {
            window.onload = function() {
                if (oldonload) {
                    oldonload();
                }
                func();
            }
        }
    }

    var blockID = "outdated"
    var closeButtonID = "btnCloseUpdateBrowser"

    addLoadEvent(function() {
        if(isBrowserOutdated(get_browser_info())) {
            var block = document.getElementById(blockID)

            //show
            block.setAttribute("style", "display: block;height: 260px")

            document.getElementsByTagName("body")[0].setAttribute("style", "overflow: hidden")

            document.getElementById(closeButtonID).onclick = function(event) {
                block.parentNode.removeChild(block)
                document.getElementsByTagName("body")[0].setAttribute("style", "overflow: auto")
            }
        } else {
            //nop
        }
    })
}

MyOutdatedBrowser()
```

**Comment by alexprg** [comment]
@pligor 
thank you man for the feedback :+1: 
Question: did you test the demo "out of the box" I mean the property you used was "transform" ? The thing is, FF15 supports transforms with prefix, did you try a property that FF15 does not support?
Change the plugin for "check browser version number" is a dead end for a generic plugin like this  :( The idea  is to be as simple and generic as possible, but let me work on that ;)
Thanks man
