### ISSUE TITLE
Greek language is missing - We would like to help

### ISSUE THREAD

**Issue by pligor** [burocratik/outdated-browser#175]
Hello to the entire team

Provided that you are using a framework with a robust internationalization system you should have a file with all the text strings used in the website http://outdatedbrowser.com/

We would like to help create the Greek translated version, i.e.: http://outdatedbrowser.com/gr

Thank you

**Comment by alexprg** [comment]
Hi @pligor 
Indeed we do.
https://github.com/burocratik/outdated-browser/tree/feature/languages-website
https://github.com/burocratik/outdated-browser/wiki/FAQ-translations-for-outdatedbrowser.com
Thank You :+1: 
Cheers
