### ISSUE TITLE
Does not support Microsoft Edge

### ISSUE THREAD

**Issue by lobby417** [burocratik/outdated-browser#176]
Microsoft Edge is considered an outdated browser.

**Comment by alexprg** [comment]
We are working on that :+1: 
They changed the detection, so we need to do more testing. Question: did you try with CSS properties or Internet Explorer browsers as reference

**Comment by alexprg** [comment]
We are working on that :+1:
They changed the detection, so we need to do more testing. 
We did try with CSS properties and it works fine, so probably we are going to dump the IE version option (even if it was easier :( )
How did you test?
Cheers

**Comment by lobby417** [comment]
I went on one of the sites that implements your function and got the error.
Perhaps they just haven't updated. I'm trying to get my http software
working on win10.

**Comment by alexprg** [comment]
I already tried to install in a old machine but didn't work properly, will have to try again with the latest build. Also the guys at @MSEdgeDev are having some trouble with RemoteIE for testing. Hope they solve the problem soon that we can do some proper testing. Without the final releaset we never now for sure if we are having problems with the plugin or not.
Did you try our demo?
once again thank you @lobby417  for the help ;)

**Comment by lobby417** [comment]
Like I said, I haven't managed to get the http server working on Windows
10, so I couldn't try the demo.

**Comment by alexprg** [comment]
ok :+1:

**Comment by alexprg** [comment]
Testes the plugin and is working fine on Edge
