### ISSUE TITLE
Translation files would better not mix html elements with literal strings

### ISSUE THREAD

**Issue by pligor** [burocratik/outdated-browser#178]
Hello to the entire team!

Inside `site_lang.php` files for translation of the website there are lots of strings that contain html elements.  
For example inside a string is this: `&lt;/body&gt;`
If this thrown inside google translate you get unexpected results which makes non technical persons not being able to translate.
Not a major issue but still some refactoring would be awesome at some time.
A suggestions is this platform which from what I recall is free for community based work: http://www.oneskyapp.com/

Keep up the good work
It would be awesome if this tool becomes mainstream

**Comment by alexprg** [comment]
Thank you for the feedback. :+1: 
We will check that website, we are really needing an Arabic translation, but has not been easy to find.
Cheers
