### ISSUE TITLE
http://outdatedbrowser.com/kr ie link change please.

### ISSUE THREAD

**Issue by crucifyer** [burocratik/outdated-browser#182]
http://windows.microsoft.com/ko-kr/internet-explorer/download-ie
"ko-kr" thank you.

**Comment by alexprg** [comment]
@crucifyer thanks for the input,
But we are using country code for URL, if we get a translation for north korea we will use .kp.
Cheers.

**Comment by crucifyer** [comment]
I can't understand.
korean translated page http://outdatedbrowser.com/kr "kr"
ie update link is http://windows.microsoft.com/en-us/internet-explorer/download-ie "en-us"
page already translated to korean
need link too. http://windows.microsoft.com/ko-kr/internet-explorer/download-ie

microsoft didn't provide ko-kp (kp-kr ?)

**Comment by alexprg** [comment]
hi,
Got what you mean. 
We are going to care of that. Cheers

**Comment by crucifyer** [comment]
thank you.
