### ISSUE TITLE
Swedish Support?

### ISSUE THREAD

**Issue by vinkla** [burocratik/outdated-browser#200]
How do I access Swedish version? When I access http://outdatedbrowser.com/sv it sends me back to the default language (en).

**Comment by brunoamorim** [comment]
@vinkla we don't have the Swedish language yet. Please check the read.me or the FAQ page https://github.com/burocratik/outdated-browser/wiki/FAQ#-translations if you would like to contribute with the Swedish language for OutdatedBrowser. We are grateful if you do so! ;)

Alternatively, you can view all the languages that we have here: http://buro.pt/cryV.

**Comment by vinkla** [comment]
Aah okay, sorry about that. I'll maybe submit a PR then.

**Comment by brunoamorim** [comment]
:+1:
