### ISSUE TITLE
Detect old android browser

### ISSUE THREAD

**Issue by alexander-schranz** [burocratik/outdated-browser#203]
How to show outdated browser message on old mobile android browser?

**Comment by alexprg** [comment]
We still don't have a mobile specific option, we are working on it.
But you can always check a css property (http://caniuse.com/) not supported for the the old browser you want and add it in the plugin:
outdatedbrowser.js
http://buro.pt/dT2z

Please do share it with us, and we may added to the plugin.
Cheers

**Comment by rejas** [comment]
Since I want to get rid of Android <= 2.3 support in my projects, I thought maybe "Basic SVG support" would be the right way to track that? See http://caniuse.com/#feat=svg

**Comment by alexprg** [comment]
hum.... but that is not a css property that you can detect. You can do it but is more complicated. I would advised a css property

**Comment by rejas** [comment]
Then I'd think transform3D should do the trick http://caniuse.com/#feat=transforms3d right?

**Comment by alexprg** [comment]
yep maybe :+1:  just test test test ;)

**Comment by rejas** [comment]
will do later this eveneing, there might be even a pullrequest coming ;-)

**Comment by alexprg** [comment]
thanks man :+1:
