### ISSUE TITLE
spelling mistake Dutch version

### ISSUE THREAD

**Issue by DJAxel** [burocratik/outdated-browser#204]
"FOR A BETTER EXPERIENCE, KEEP YOUR BROWSER UP TO DATE. CHECK HERE FOR LATEST VERSIONS." (at the top of outdatedbrowser.com) has been translated to "HOU VOOR EEN BETERE ERVARING JE BROWER UP TO DATE. KLIK HIER VOOR DE LAATSTE VERSIES". Firstly, the word "hou" should be spelled "houd", as the infinitive is "houden". Secondly, the period at the end of the sentence is missing.

**Comment by alexprg** [comment]
Thank you, 
Just changed, but you can always submit any changes here: 
https://github.com/burocratik/outdated-browser/tree/feature/languages-website
and we just have to merge the pull request.
Cheers :+1:
