### ISSUE TITLE
Chrome download link is incorrect

### ISSUE THREAD

**Issue by addzies** [burocratik/outdated-browser#205]
The link to download Chrome should go to: https://www.google.com/chrome/browser/desktop/

It currently goes to: https://www.google.com/chrome/, which looks like this on IE9:

![screen shot 2015-11-20 at 2 59 04 pm](https://cloud.githubusercontent.com/assets/10556691/11313067/7c8d638e-8f97-11e5-8ea6-92eee86e4e02.png)

**Comment by alexprg** [comment]
@addzies thank you :+1: 
They are always changing the landing pages. Hard to keep track.
cheers
