### ISSUE TITLE
Project page without language in url shows PHP error

### ISSUE THREAD

**Issue by DuckThom** [burocratik/outdated-browser#206]
The link http://outdatedbrowser.com/project productes the following php error:

![Imgur](http://i.imgur.com/TZqUFGC.png)

If the language is added to the url, the page works fine.
http://outdatedbrowser.com/en/project or http://outdatedbrowser.com/nl/project

**Comment by alexprg** [comment]
@DuckThom thanks
We have just fixed that bug.
cheers
