### ISSUE TITLE
Checking against other browsers than IE

### ISSUE THREAD

**Issue by HugoHeneault** [burocratik/outdated-browser#213]
Hi there, 

Thanks for your great tool!

I need to show the notice for others browsers (as old ios browsers, for example). 
But it doesn't seems to work using the transform property... Any ideas? :(

**Comment by alexprg** [comment]
Hi @HugoHeneault 
If you targeting mobile OS, that is something that we are planing to do in the future.
The properties that we are targeting maybe aren't enough to your case. I would suggest going to http://caniuse.com/ and see what properties may help you in your situation. Then you just need to do some small changes in the outdatedbrowser.js for that property. Do not forget to share it with us here :) 
Hope it helped 
cheers
