### ISSUE TITLE
Up to date Chrome on Ubuntu 14.04 triggers the "Outdated Browser" message

### ISSUE THREAD

**Issue by budinschi** [burocratik/outdated-browser#214]
I haven't looked into the js file, so I dont know if you're relying on feature detection, or user agent, or both ( recommended ).. but here's my Chrome user agent

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36

**Comment by alexprg** [comment]
hi @budinschi 
Strange indeed! we are just using feature detection, so such a thing should not happen . Can you send us a print screen or the link where you using the plugin?
Cheers

**Comment by budinschi** [comment]
hi @alexprg
I wasn't the one using the plugin, the message appeared on upwork.com seems like they're using it ( still using ). I just visited upwork again, using the same browser and version, the message doesn't appear anymore. Problem solved itself ?

**Comment by alexprg** [comment]
@budinschi Thank you anyway for the feedback.
Indeed I contacted upwork.com at the 29th january about this problem. 
All is well and that is good.
Cheers
