### ISSUE TITLE
Question: Can we use _GET parameters to remove a browser from the website?

### ISSUE THREAD

**Issue by vicentor** [burocratik/outdated-browser#217]
We have a hardcore jQuery intranet in the collective insurance world and we recently found out that IE11 doesn't even support JavaScript objects properly. We love this plugin, but we're **so** done with IE. It thinks that the returned object is some kind of anonymous function instead of an object. (SCRIPT65535: Argument obligatoire)

**Something like http://outdatedbrowser.com/fr?except=ie**

Thank you for any follow-up!

**Comment by vicentor** [comment]
I'd like to add that Edge works very well... I thought they shared the same JS engine.

**Comment by alexprg** [comment]
@vicentor so you want an option that a certain browser does not appear?
Edge as a totally different engine, is webkit based.

**Comment by vicentor** [comment]
Exactly @alexprg! We'd like to redirect our users to the website if they have IE11, but if they see IE in the options, they will think they only have to update it. We want them to change browser entirely.

What do you think?

**Comment by alexprg** [comment]
@vicentor I really feel your pain ehehehehe
Maybe is something that we may considered in a future update.
Cheers
