### ISSUE TITLE
Not really actuall ;)

### ISSUE THREAD

**Issue by nerdcoat** [burocratik/outdated-browser#221]
I visited the site for the first time, but FF44 is not the actuall. I use 45.0.1 :)
But its a great project, so keep up the great work!

**Comment by zedtux** [comment]
+ 1

**Comment by alexandre-works** [comment]
@nerdcoat  Thank you :+1: 
You right we are a little behind, sometimes is hard to keep track in all the new updates and stats. Cheers :)
