### ISSUE TITLE
Outdated Chrome Logo

### ISSUE THREAD

**Issue by kristianserrano** [burocratik/outdated-browser#222]
This isn't really an issue as much as it is a suggestion, and I couldn't find any other way of reaching out. Chrome has a [newer logo based on Material Design](http://logos.wikia.com/wiki/Google_Chrome#2015-present.2C_2014-present_.28Android.29.2C_2015-present_.28iOS.29) with which you might want to replace the current logo on [outdatedbrowser.com](http://outdatedbrowser.com). Since we're trying to keep up with "current browsers," it might be worth updating the logo. :-)

**Comment by brunoamorim** [comment]
Hi @kristianserrano, thanks for your message. But, in fact, I think we have the last version of the Google Chrome. If you view this image in detail http://outdatedbrowser.com/public/imgs/browsers-bg.png you can see the last version of the logo.

Thanks!
B.

**Comment by kristianserrano** [comment]
It's actually not the current logo. Your version is pre-Material Design with highlights on the surface, whereas the current version is clearly Material Design using a flatter design with shadows.

**Comment by brunoamorim** [comment]
You are right and we've just updated to the newer logo!

Thanks for your support.
B.
