### ISSUE TITLE
Outdated IE Logo

### ISSUE THREAD

**Issue by kristianserrano** [burocratik/outdated-browser#223]
After resolving the Chrome logo being outdated, I checked the others and realized the IE logo you have is for IE9. The current logo for IE11 is here:
http://logos.wikia.com/wiki/Internet_Explorer#2012-2015_.28Internet_Explorer_10_-_11.29

(For what it's worth, Opera, Safari, and Firefox seem to be current.)

**Comment by Kum0ri** [comment]
Hi @kristianserrano. Thanks for pointing that!

We updated the logo of ie with the latest design.

Cheers,
daniel.
