### ISSUE TITLE
Close Button Not Working

### ISSUE THREAD

**Issue by pixeltopress** [burocratik/outdated-browser#225]
Hello,

Newby here. For some reason the close button is not working for me? I'm testing this locally and using the plugin without AJAX calls. Is it because I've forced it to work on modern browsers via: $("#outdated").show()

Any ideas? Thank you so much!

Also if there's a better way to test locally please let me know.

**Comment by alexandre-works** [comment]
Hi @pixeltopress,
Indeed you are right. If you force show(), the js is never triggered for the button close event and it will not work.
The best way to test and to be sure that will work is in a virtual machine with the version of the browser you want to test, but you can always go to the outdatedbrowser.js and put a property that your corrent browser doesn't support: line 29.
Hopefully soon an option for testing will be implemented (#190).
tell me if it works ;)
cheers
