### ISSUE TITLE
Notice not showing up on some old browsers

### ISSUE THREAD

**Issue by zedtux** [burocratik/outdated-browser#229]
Outdated browser seems to no more work for some old version of old browsers :

**Internet Explorer**

 - **6 & 7: Banner is NOT displayed (but I did the Ajax way, so it seems "normal")**
 - 8: Banner is displayed
 - 9: Banner is displayed
 - **10: Banner is NOT displayed**
 - 11 and more: Banner is not displayed which is normal

**Firefox**

 - **From version 3 to 45: Banner is NOT displayed**

**Chrome**

 - **From version 16 to 48: Banner is NOT displayed**

For Chome, it's not a big issue as my website (using CSS2 & 3/HTML5) is working fine even with version 16!

**Opera**

 - **From 10.6 to 35: Banner is NOT displayed**

**Safari**

 - **From 4 to 9: Banner is NOT displayed**

I'm using a modified version from the version 1.1.3 with the following diff:

```diff
diff outdatedbrowser.*
103c103
<     if (!supports('' + cssProp + '')) {
---
>     if (!supports('' + cssProp + '') && document.cookie.replace(/(?:(?:^|.*;\s*)outdatedclosed\s*\=\s*([^;]*).*$)|^.*$/, "$1") !== "true") {
147a148
>             document.cookie = "outdatedclosed=true; expires=Fri, 31 Dec 9999 23:59:59 GMT; path=/";
216,221c217,225
< 
< 
< 
< 
< 
< 
---
> //call plugin function after DOM ready
> $(document).ready(function() {
>   outdatedBrowser({
>       bgColor: '#f25648',
>       color: '#ffffff',
>       lowerThan: 'transform',
>       languagePath: ''
>   });
> });
```

(The only change is to write a cookie when the banner is closed)

**Comment by alexandre-works** [comment]
hi @zedtux 
Thank you so much for your input, and we are going to analyse you problem asap.
Just some questions:
- These tests you did, are you using the "demo" or in a project of your own?
- The plugin is not working only in your modified version? Did you test with our version without your alterations?

NOTE: we did some tests some time ago for cookies, and we had some real problems the way older browsers handle cookies. For older browsers like IE6, 7 and the counterparts Chrome, Safari and FF there was no universal way to handle cookies, and we had strange bugs. Is something that we need to work on. What we did find was: for the plugin work in very old browsers (and that is it's purpose) we had to keep it as simple as possible, more options = less browser support (see our faqs we talk a little about that). Anyway the cookies options is something that we have to work on.
thank you for your feedback :+1:

**Comment by zedtux** [comment]
> These tests you did, are you using the "demo" or in a project of your own?

In a project of my own.

> The plugin is not working only in your modified version? Did you test with our version without your alterations?

No, I didn't.

I will redo my testing using your demo and update my ticket.

**Comment by zedtux** [comment]
Just to ease my tests, I have built the following Docker project: https://github.com/YourCursus/docker-outdated-browser-demo

**Comment by zedtux** [comment]
So I have deployed my Docker image here: http://outdated-browser-demo-3b90191d-1.69c5117b.cont.dockerapp.io:32799/
I'm gonna redo my testing now.

**Comment by zedtux** [comment]
I just realize that I forgot the CSS... I have to rebuild the Docker images.

**Comment by zedtux** [comment]
The new Docker image URL (outdated browser demo version 1.1.3): http://outdated-browser-demo-3b90191d-1.14b79fc2.cont.dockerapp.io:32803/

**Comment by zedtux** [comment]
Testing of the library using the demo app:

**Internet Explorer**

 - 6, 7, 8 and 9: Fully working
 - **10 and 11: Banner do NOT appears, excepted with the "Compatibility View" mode enabled**
 - 12 and 13: Banner doesn't appears

**Firefox**

 - 3: Fully working
 - **From 3.6 to 45 : Banner do NOT appears**

**Chrome**

 - **From 15 to 49: Banner do NOT appears**

**Opera**

 - **From 10.6 to 36: Banner do NOT appears**

**Safari**

 - **From 4 to 9: Banner do NOT appears**

Here is my testing check list:

 1. Open the URL in the web browser (http://outdated-browser-demo-3b90191d-1.14b79fc2.cont.dockerapp.io:32803/)
 2. Click the first link "Default use: Ajax + English"
 3. Check if the banner appears
 4. Return to the homepage
 5. Click the second link "Ajax + Portuguese"
 6. Check if the banner appears
 7. Return to the homepage
 8. Click the third link "No ajax + Français"
 9. Check if the banner appears
 10. Return to the homepage
 11. Click the fourth link "jQuery version that supports IE6 to IE8 (default use)"
 12. Check if the banner appears
 13. Return to the homepage
 14. Click the last link "Design example (no ajax)"
 15. Ensure the banner appears

**Comment by alexandre-works** [comment]
Hi,
And the property you used was? I did a test again (not all the browsers you did) and it was working fine :(
On IE 10, 11 was working fine according to the property i used.
Sorry

**Comment by zedtux** [comment]
What do you mean by "property"? I gave all the testing procedure, the repo with the code and a running image (well ... it seems down now).

**Comment by alexandre-works** [comment]
I mean the css property you used: 
https://github.com/burocratik/outdated-browser , 
**6.Targeting browsers:**

**Comment by zedtux** [comment]
Ha ok! The source code of the demo I used is here https://github.com/YourCursus/docker-outdated-browser-demo as mentioned before.
I took the demo folder from the https://github.com/burocratik/outdated-browser repository which seems to [use the `transform` css property](https://github.com/YourCursus/docker-outdated-browser-demo/blob/master/demo/jquery.html#L52).

**Comment by alexandre-works** [comment]
ok, so the outputs you got are correct for the property you used.
Thank you
Cheers
