### ISSUE TITLE
Does this detect old Safari (etc)?

### ISSUE THREAD

**Issue by nruth** [burocratik/outdated-browser#233]
Does this detect Safari versions before flex-box was added? The readme and FAQ only talk about Internet Explorer.

The same question is interesting for old Firefox, Chrome, etc, but Safari especially because it's an OS upgrade instead of evergreen, so some people don't do it.

**Comment by alexandre-works** [comment]
Hi there 
We do talk about IE just because is the most common used, but we do not use browser sniffing:
Check point 6. https://github.com/burocratik/outdated-browser

So you can check if the properties we use can help you in your detection.
Anything else just ask 👍 
cheers

**Comment by atu-record** [comment]
this issue sould be reopened. its important to implement a flex & grid option for older FF Chome & safari
