### ISSUE TITLE
Outdated Browser popup doesn't show up IE7 and below

### ISSUE THREAD

**Issue by KyoriAsh** [burocratik/outdated-browser#238]
Hi, I recently implemented the javascript and CSS into a wiki, which forced me to modify the code "abit", although are almost the same. I can force test the popup using IE11's Developer Tools by emulating IE9 and below. The only result is IE 8 and 9 is showable, while IE7 and below doesn't popup. Can anyone enlighten me what did I done wrong.

http://zh.kancollewiki.net/wiki/MediaWiki:Common.js <- Javascript
http://zh.kancollewiki.net/wiki/MediaWiki:Common.css <- css, should be no problem actually
http://zh.kancollewiki.net/wiki/Widget:OutdatedBrowser <- using Widget to use the raw code, which implemented in the header of Mediawiki:Anonnotice and Mediawiki:Sitenotice

**Comment by brunoamorim** [comment]
Hi @KyoriAsh, you must do the test with a native Internet Explorer browser or a Virtual Machine. Using the Developer Tools it's not reliable. 
I only guarantee you that the browser detection is fully working. ;)

**Comment by KyoriAsh** [comment]
@brunoamorim Unfortunely, this was also tested in Windows XP's Internet Explorer 6, and the result is the same

**Comment by brunoamorim** [comment]
@KyoriAsh are you using the right properties to target the desire browser? Read carefully the follow point: http://buro.pt/ib7q on the readme file: https://github.com/burocratik/outdated-browser

**Comment by KyoriAsh** [comment]
`addLoadEvent(function(){
    outdatedBrowser({
        bgColor: '#f25648',
        color: '#ffffff',
        lowerThan: 'IE11',
        languagePath: ''
    })
});`
