### ISSUE TITLE
Where is translated page content?

### ISSUE THREAD

**Issue by szepeviktor** [burocratik/outdated-browser#239]
I've found that `Ccsak OS X` is really `Csak OS X` in Hungarian.
http://outdatedbrowser.com/hu

But it is not in this repo.
Please help.

**Comment by Kum0ri** [comment]
Hi @szepeviktor ! Thanks for the correction, we already updated the typo.

Thanks again.
Cheers,
daniel.

**Comment by szepeviktor** [comment]
Thanks.
Could you tell me whether the website's source is public?

**Comment by Kum0ri** [comment]
@szepeviktor  the website is not public :) Only the plugin is open source.
