### ISSUE TITLE
Versions inconsistence

### ISSUE THREAD

**Issue by Eolga** [burocratik/outdated-browser#240]
Good day,
I've met with the next issue.
On http://outdatedbrowser.com/en site Google Chrome the latest version is shown as 51.
![google chrome latest version](https://cloud.githubusercontent.com/assets/20969537/17587945/1fa85062-5fd4-11e6-9d9b-818a14811122.png)
But 52 version is installed indeed.

**Comment by brunoamorim** [comment]
Hi @Eolga, thanks for notice that. We've fixed the version number on Chrome and Firefox and Opera too.

Cheers!
Bruno.
