### ISSUE TITLE
The download link of chrome doesn't work in http://outdatedbrowser.com/zh-cn

### ISSUE THREAD

**Issue by shery15** [burocratik/outdated-browser#241]
[http://outdatedbrowser.com/zh-cn](url) looks prety.
I have been using outdated-browser for a long time,very useful.
But the download link of chrome doesn't work in [download link of chrome doesn't work in http://outdatedbrowser.com/zh-cn](http://outdatedbrowser.com/zh-cn).As we all know,network is bad from within China,we can not approach Google.

Can I download the source code form the site [ http://outdatedbrowser.com](http://outdatedbrowser.com),and fix it for within China,non commercially?

**Comment by brunoamorim** [comment]
Sorry @shery15 but the source code of the website isn't available.

**Comment by shery15** [comment]
What a pity!
The UI of [http://outdatedbrowser.com](http://outdatedbrowser.com) looks great!
OK, I'll find another way out.

**Comment by brunoamorim** [comment]
Hi @shery15, thanks for using Outdated Browser.
The only component that is open source is the Outdated Browser plugin, not the website. Otherwise, we'll end to have a bunch of Outdated Browser and loses the quality control.
Can you please tell us what's intend to do within China with this tool so can we analyse and adapt the tool accordingly the restrictions?

Thank you!

**Comment by shery15** [comment]
When using Outdated Browser plugin, I would open the website [http://outdatedbrowser.com/zh-cn](http://outdatedbrowser.com/zh-cn) to show Browser download links  in most cases. Because of Google's exit from China, download link of chrome doesn't work within China, and most users can not fix this issue. So, if we can change the download link to a third party platform, it would be very friendly to the user from China.

Thanks for your response!

**Comment by brunoamorim** [comment]
Hi @shery15 , thank for your help.
Ok, could you paste here the link that works within China?

Thank you!

**Comment by shery15** [comment]
Such as [http://down.tech.sina.com.cn/content/40975.html](http://down.tech.sina.com.cn/content/40975.html) and [http://rj.baidu.com/soft/detail/14744.html](http://rj.baidu.com/soft/detail/14744.html) work well works within China.
