### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by chriszarate** [burocratik/outdated-browser#249]
Currently, https://outdatedbrowser uses a certificate issued to `*.webfaction.com` and generates a browser error.

Consider using [Let's Encrypt](https://letsencrypt.org/) to support HTTPS.

**Comment by Deadload** [comment]
Hi @chriszarate 
We finally added the ssl for the outdatedbrowser.com with Let's Encrypt :)
It worked fine

Thanks for your suggestion.

Joao

**Comment by brunoamorim** [comment]
@chriszarate unfortunately we had to remove the https since some users are experience troubles in access to outdatedbrowser website with older browsers (https://twitter.com/volgensbartjes/status/814019344057454592) and the target of this tool is older browsers. ;)

**Comment by chriszarate** [comment]
@brunoamorim Is that because you are using [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) to implement HTTPS? If so, any way to help / sponsor a dedicated IP for this project?
