### ISSUE TITLE
IE8 Load Issue - http://outdatedbrowser.com/en

### ISSUE THREAD

**Issue by beausif** [burocratik/outdated-browser#258]
When testing the website (http://outdatedbrowser.com/en) on IE8, the page does not load correctly.

The only thing that is being shown is a div with a red background.

The child element is still set to hidden so something is not firing correctly.

**Comment by alexandre-works** [comment]
Hi there,
Maybe you have some inherit css that is hidden that content.
Can you show us a print screen of the css that is associated with the child elements that aren't shown?
Cheers

**Comment by beausif** [comment]
Here is a screenshot of the page and the css.

The html markup for IE8 is different than other browsers, this looks like it is due to a missing </nav> tag.

The right menu nav bar contains div.pusher. It also contains a duplicate div.keep_calm and duplicate script tags that appear latter on in 

This is causing the browser list to be hidden off of the screen with the nav bar.

![outdatedbrowserie8issue](https://cloud.githubusercontent.com/assets/15196531/22258473/b739953e-e22f-11e6-9323-f118057adc34.PNG)

**Comment by Kum0ri** [comment]
Hi @beausif ,

Thank you very much for the bug report.

We already spotted the problem and will deploy a fix now.

Thanks again,
Cheers,
daniel.
