### ISSUE TITLE
PHP error due to missing stat file

### ISSUE THREAD

**Issue by andrepearce** [burocratik/outdated-browser#259]
I am experiencing the following php error when visiting your site (http://outdatedbrowser.com/en).

```
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  fopen(./public/stats-files/browser-ww-monthly-201701-201702-bar.csv): failed to open stream: No such file or directory</p>
<p>Filename: views/home.php</p>
<p>Line Number: 64</p>
```

It seems there is an issue with the stats file.

**Comment by JDW1** [comment]
I just confirmed that problem exists.

**Comment by andrepearce** [comment]
This looks to be resolved now.

**Comment by JDW1** [comment]
As of today, July 31, 2017, I noticed the PHP error is back:

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  fopen(./public/stats-files/browser-ww-monthly-201707-201707-bar.csv): failed to open stream: No such file or directory</p>
<p>Filename: views/home.php</p>
<p>Line Number: 73</p>
