### ISSUE TITLE
there is an error on the top of http://outdatedbrowser.com/en

### ISSUE THREAD

**Issue by sajjad-shirazy** [burocratik/outdated-browser#262]
> A PHP Error was encountered
Severity: Warning
Message: fopen(./public/stats-files/browser-ww-monthly-201702-201703-bar.csv): failed to open stream: No such file or directory
Filename: views/home.php
Line Number: 64

**Comment by Deadload** [comment]
Hi @sajjad-shirazy, thank you for your input...
We already corrected the issue :)
