### ISSUE TITLE
update npm package to latest version and add npm as an install option to README.md

### ISSUE THREAD

**Issue by udos** [burocratik/outdated-browser#265]
npm is pretty convenient for package installation and it's a pity that it does not contain the latest version

- https://www.npmjs.com/package/outdated-browser

would be good to also include it to README.md as an install option

thanks

**Comment by brunoamorim** [comment]
@udos this is a issu that as already been discussed on this topic: https://github.com/burocratik/outdated-browser/issues/234#issuecomment-303296842

Thanks.
