### ISSUE TITLE
PHP error on website

### ISSUE THREAD

**Issue by danbohea** [burocratik/outdated-browser#272]
The website is currently showing the following error and the usage stats for each browser have failed to load:

```
A PHP Error was encountered
Severity: Warning
Message: fopen(./public/stats-files/browser-ww-monthly-201706-201707-bar.csv): failed to open stream: No such file or directory
Filename: views/home.php
Line Number: 72
```
Looks like your PHP script is pointing at a non-existent CSV file?

**Comment by brunoamorim** [comment]
@danbohea thanks for the bug report. Error fixed! ;)
