### ISSUE TITLE
Use https for outdatedbrowser.com 

### ISSUE THREAD

**Issue by joshreid** [burocratik/outdated-browser#275]
Hi there

Would you consider implementing SSL Cert and serving outdatedbrowser.com website over https protocol?

**Comment by brunoamorim** [comment]
Unfortunately we had to remove the https since some users are experience troubles in access to outdatedbrowser website with older browsers (https://twitter.com/volgensbartjes/status/814019344057454592) and the target of this tool is for older browsers. ;)
