### ISSUE TITLE
Some of the demo images aren't what I expected!

### ISSUE THREAD

**Issue by AshboDev** [burocratik/outdated-browser#282]
So I was checking out the demo's, and came across these little gems:

**Default**
IE9 - Win7: http://buro.pt/Win3 - Something about women getting wet
IE8 - WinXP: http://buro.pt/WiRz - Random hold music?
IE6 - XP: http://buro.pt/WieT - Bottle of german beer I think

**Ajax Portuguese**
IE6 - XP: http://buro.pt/WiWB - Valve/Steam player profile

**No Ajax French**
IE6 - XP: http://buro.pt/Wj2x - Screenshot from iPhone

**Comment by Kum0ri** [comment]
Hi there @AshboDev ,

Thank you for these findings! Looks like some broken links were still in the there. 

Already changed it.

cheers,
daniel
