### ISSUE TITLE
Language message depending on locale

### ISSUE THREAD

**Issue by 01Kuzma** [burocratik/outdated-browser#283]
Hi there!
Is it possible to serve language message depending on browser's locale or/and depending of website's URL? 
For example:
```
www.website.com/ -> give default message
www.website.com/en -> give message in English
www.website.com/x -> give message in xx language
```

Thank you!

**Comment by Kum0ri** [comment]
Hi there!

One solution could be, checking the url before you initialise outdatedbrowser and load the appropriated language file -> http://buro.pt/e4fhoo

**Comment by 01Kuzma** [comment]
Could you provide a working example?

**Comment by Kum0ri** [comment]
You can check the url with https://www.w3schools.com/js/js_window_location.asp and if you detect a language code load the plugin with the language that is present in the url.

You can check the documentation to see how to load the language files -> https://github.com/burocratik/outdated-browser

Good luck!

**Comment by 01Kuzma** [comment]
Thank you!
