### ISSUE TITLE
Private network version of http://outdatedbrowser.com page ?

### ISSUE THREAD

**Issue by mcarbonneaux** [burocratik/outdated-browser#286]
I have many application that are used in private network that don't have access to internet, and they need page like http://outdatedbrowser.com but hosted on private network (with no clood version of css and js file) ?!

And also with not all possibility of browser (some of them are not autorized on this private network) to download and with private network link to this browser download page ?!

**Comment by brunoamorim** [comment]
Hi @mcarbonneaux sorry but this project is only for online usage.
Thank you and have a nice day!

**Comment by mcarbonneaux** [comment]
Why?
