### ISSUE TITLE
https on http://outdatedbrowser.com/

### ISSUE THREAD

**Issue by xstya** [burocratik/outdated-browser#287]
Hi, please add support for https on http://outdatedbrowser.com/. Thank you.

**Comment by iss0** [comment]
Why is this not fixed? It is a real bummer to not have https on any website in 2018. Especially since certificates are free to get via letsencrypt. Is this planned soon? Otherwise I'll change the link to a different site I guess.

**Comment by brunoamorim** [comment]
Because IE6 doesn't support SSL certificates. We already have it and in times and created several conflits. Thank you.

**Comment by selrond** [comment]
There's no hope on this world for people using IE6 - but seriously - is it worth sacrificing everybody's else security for those few unfortunate?

**Comment by FranklinYu** [comment]
@brunoamorim So the comment above didn’t change your mind? Among the users this website is targeting (using non-modern browser), how many are still using IE 6? I understand if it was IE 8 (latest supported on Windows XP), but IE 6?

**Comment by brunoamorim** [comment]
@FranklinYu @selrond the main goal to make this project alive was for targeting IE6 users. So for us doesn't make any sense ignore this browser now. We are looking for alternatives. Thank you.

**Comment by xstya** [comment]
Could you create a version with https support on a separate domain?
