### ISSUE TITLE
HTTPS Live website

### ISSUE THREAD

**Issue by shealavington** [burocratik/outdated-browser#306]
Hey, I'm using outdated-browser, I've noticed that visiting the HTTPS version of the website is causing an error, whereas the HTTP version still works. I thought a GH ticket would be the best way of informing you about this. :)

**Comment by wottpal** [comment]
@burocratik I would love to link my visitors to your beautiful service but will not do so when you are still using HTTP :(

**Comment by shealavington** [comment]
Unmaintained issue board, I'm clearing out my raised but unfixed/untouched issues. Someone else is free to raise this issue again but as their own, if the issue still persists.
