### ISSUE TITLE
Remove percent and put browsers randomly

### ISSUE THREAD

**Issue by AntoineTurmel** [burocratik/outdated-browser#4]
Web Browsers should appear randomly and you could remove % of use.

If you want to keep % it's fine but put more details about the web browser (for example better user privacy for Firefox, Touch/Metro interface for IE etc.)

**Comment by zandergrin** [comment]
Except it's not sorted by popularity - IE is shown before edge, which has fewer users.

I don't think we have an issue with being sorted by popularity - it's just that chrome is shown fullscreen at the start of the transition. It appears to be a clear self-perpetuating-dominance chrome bias, which we wouldn't want to present to our clients.
